### ISSUE TITLE
Card not showing alarms

### ISSUE THREAD

**Issue by kimonm** [DurgNomis-drol/google_home_timers_card#11]
**Describe the bug**
Alarms are set for a google home. I see them in the developers tool, e.g.,:
![image](https://user-images.githubusercontent.com/40135180/112707238-247ed680-8e67-11eb-8a12-78fb0dcb8cea.png)

However, they are not listed in the timers card:
![image](https://user-images.githubusercontent.com/40135180/112707261-49734980-8e67-11eb-882a-d9bf0c18badc.png)

I double checked that the card has the correct sensors listed, and it's been more than 8 hours but the alarms don't show up. The alarms were set before I last rebooted HA (if it makes a difference). I'm not sure when it should refresh, or how to force it.

**To Reproduce**
Unclear.

I'm running HA 2021.3.4, Google Home 1.1.0, latest googletimers-card.js
(Btw, there doesn't seem to be version comment in the code. That would be useful, I think.)

Thanks.

**Comment by DurgNomis-drol** [comment]
First of all. Great issue! 

This is because of breaking changes in the `google_home` integration and i have not updated this card yet as somethings have not been sorted out over there. Hopefully I can update this either tomorrow or Monday 😊 Stay tuned!

**Comment by DurgNomis-drol** [comment]
@kimonm 

Can you please try the latest master. It should now be updated to work with latest version of `google_home`. 😄

**Comment by kimonm** [comment]
No luck. I get the same behavior as described above. Alarms and timers are not showing.

**Comment by DurgNomis-drol** [comment]
Did you clear browser cache? 😊

**Comment by kimonm** [comment]
Well duh. :) That worked. Alarms and timers are showing again. Thanks!

**Comment by DurgNomis-drol** [comment]
No problem 😊 Glad to here that it works 🎉
