### ISSUE TITLE
Add visual add/edit card 

### ISSUE THREAD

**Issue by daften** [DurgNomis-drol/google_home_timers_card#25]
**Is your feature request related to a problem? Please describe.**
Now the card can only be configured through yaml, configuring it through UI would be nicer.

**Describe the solution you'd like**

A graphic configuration for the card.

**Describe alternatives you've considered**

Using yaml, and it works fine as-is, but it could be nicer/better :)

**Comment by DurgNomis-drol** [comment]
As the main integration does not work for me anymore, i won't be updating this unfortunately.

**Comment by JOHLC** [comment]
> As the main integration does not work for me anymore, I won't be updating this unfortunately.

Just a heads up, this integration has become much more reliable in recent history
