### ISSUE TITLE
Display problem, possibly due to 24 hour clock setting

### ISSUE THREAD

**Issue by deepcoder** [DurgNomis-drol/google_home_timers_card#7]
Thank you for your work on this project, very useful!

I have this timer running:

```
fire_time: 1615584610
id: timer/22cf8018-489d-9f30-bc1e-f4c10cd3c79f
local_time: 2021-03-12 13:30:10
local_time_iso: 2021-03-12T13:30:10-08:00
duration: 0:05:00
device: Living Room Speaker next_timer
integration: google_home
friendly_name: Living Room Speaker next_timer
icon: mdi:timer-sand
```

and the display via your card shows:

```
    - type: custom:googletimers-card
      entity: sensor.living_room_speaker_timers
      title: Livingroom Google Home Timers
```
<img width="408" alt="google-time-problem" src="https://user-images.githubusercontent.com/1409547/111000523-0e392c80-8337-11eb-9e2c-54122f079f0b.png">

It correctly shows 'Timer Done' when the timer finishes the 5 minutes it was set for.

**Comment by DurgNomis-drol** [comment]
Happy that you find it useful!

It seems to be how I calculate remaining time. Something to do with timezones. I'm trying to fix it now, will return with answer when i have on 😄

**Comment by DurgNomis-drol** [comment]
Should be fixed now.  Was a problem with how i displayed the time after subtracting.

Can you please test it and give feedback 😄 Remember to download the new one from master and clear browser cache. 

Browser cache can cleared by activating developer mode for chrome (Ctrl + Shift + i)  and then right clicking the refresh icon in upper left corner and choose the last option.

**Comment by deepcoder** [comment]
Can you give an example of proper yaml for configuration.yaml ?
what 'type' should be specified? I do not believe that 'javascript-module' is valid in yaml. I tried it with 2021.3.3 and when I restarted HA, it put system into safe mode... and that proceeded to hose up a bunch of stuff that took a number of restarts to straighten out. Thx for your work on this card and your help!

```
#    https://github.com/DurgNomis-drol/google_home_timers_card
    # - type: javascript-module # not valid
    # - type: module
    # - type: js
      url: /local/custom-lovelace/google_home_timers_card/googletimers-card.js
      
```

**Comment by DurgNomis-drol** [comment]
@deepcoder I don't personally use yaml mode for lovelace. But it should just be like this:
```yaml
lovelace:
  mode: yaml
  resources:
    - url: /local/googletimers-card.js
      type: module
```

But js modules is on there way out in HA as I understand it. At some point I am gonna rewrite it to be in typescript, but i need to learn it first. :smile:

**Comment by DurgNomis-drol** [comment]
@deepcoder Did you find a fix?

**Comment by deepcoder** [comment]
Thanks for the fix and yaml documentation. I have yet to try it as the underlying google timer add in continue to have problems for me. I will try and post results as soon as I can get the add in running stable.
If the yaml you put above is correct, you should correct the documentation on the github readme.md file:
```
and then input /local/googletimers-card.js and change resourcetype to javascript-module
```
because when I tried :

```
- type: javascript-module
```

it put HA into 'safe' mode at next restart of HA. And this caused a cascade of issues that I had to work thru making it difficult to get back to testing your card.....

Thanks again for your work!

**Comment by DurgNomis-drol** [comment]
@deepcoder When you get a chance to test it again, please leave some feedback. In the mean time i will add a note to the readme so people don't run into the same problem as you have done.

Home Assistant calls it a `javascript-module` in UI and a `module` in the underlaying `ui-lovelace.yaml` file.

**Comment by ZWOOKY-Code** [comment]
Hi

If had a similar problem with the display. If changed in my local-code the line below from STATE_ON to ...UNKNOWN.

```
    // if (state.state == STATE_ON || state_alarms.state == STATE_ON) {
    if ( state.state != STATE_UNKOWN || state_alarms.state != STATE_UNKOWN) {

```
in the state of my timers is a time and not ON ... so it will never be true
`state:  2021-03-26T02:00:17+01:00
`
Example of my entry:
```
timers:
  - timer_id: timer/15447f01-4190-547e-1c03-d2a0281cb2b3
    duration: '0:58:40'
    fire_time: 1616720417
    label: null
    local_time: '2021-03-26 02:00:17'
    local_time_iso: '2021-03-26T02:00:17+01:00'
integration: google_home
friendly_name: Living Room pair timers
icon: 'mdi:timer-sand'
device_class: timestamp

```

**Comment by DurgNomis-drol** [comment]
Thanks for the feedback.

This is because i haven had the time to update it to use the newest version of Google home which was just released last night 🙂 Breaking changes was introduced and i push fix very very soon.

**Comment by DurgNomis-drol** [comment]
@deepcoder i will close this issue for now. If you are still having this issue you can reopen it again. 😊

@ZWOOKY-Code Please see #8 for updates on your issue.
