### ISSUE TITLE
Inconsistency in font & sizing?

### ISSUE THREAD

**Issue by kimonm** [DurgNomis-drol/google_home_timers_card#9]
I'm running HA 2021.3.4 and core-2021.3.4 with just the default Lovelace theme. (Browser is Chrome 89.0.4389.90)
For your cards, the title & body  fonts and sizes differ from other cards. I don't know if this is intended behavior or not, so I don't know if this is a bug or a feature :)  (I see font sizes in the code, but not the font itself.)

Here's a screen shot comparing to a couple of other cards:
![image](https://user-images.githubusercontent.com/40135180/111845076-65a04500-88c1-11eb-8e9a-cf601960896d.png)

**Comment by DurgNomis-drol** [comment]
Thank for the feedback 🙂

It is supposed to look different from those cards you are comparing it it to.(In fact those are actually the samme underlaying card).

It is meant to look more like this car: [Entity card](https://www.home-assistant.io/lovelace/entity/)

The font is the same as every where else. Font weight is different then the cards you are comparing to, that's the reason they look different. 😊
